FUNC LABEL 0
    MOV STK A VAL 1
    MOV STK B VAL 1
    MOV STK C VAL 1
    MOV STK D VAL 1
    MOV STK E VAL 1
    MOV STK F VAL 1
    MOV STK G VAL 1
    MOV STK H VAL 1
    MOV STK I VAL 1
    MOV STK J VAL 1
    MOV STK K VAL 1
    MOV STK L VAL 1
    MOV STK M VAL 1
    MOV STK N VAL 1
    MOV STK O VAL 1
    MOV STK P VAL 1
    MOV STK Q VAL 1
    MOV STK R VAL 1
    MOV STK S VAL 1
    MOV STK T VAL 1
    MOV STK U VAL 1
    MOV STK V VAL 1
    MOV STK W VAL 1
    MOV STK X VAL 1
    MOV STK Y VAL 1
    MOV STK Z VAL 1
    MOV STK a VAL 1
    MOV STK b VAL 1
    MOV STK c VAL 1
    CAL VAL 1
    RET
FUNC LABEL 1
    MOV STK A VAL 1
    MOV STK B VAL 1
    MOV STK C VAL 1
    MOV STK D VAL 1
    MOV STK E VAL 1
    MOV STK F VAL 1
    MOV STK G VAL 1
    MOV STK H VAL 1
    MOV STK I VAL 1
    MOV STK J VAL 1
    MOV STK K VAL 1
    MOV STK L VAL 1
    MOV STK M VAL 1
    MOV STK N VAL 1
    MOV STK O VAL 1
    MOV STK P VAL 1
    MOV STK Q VAL 1
    MOV STK R VAL 1
    MOV STK S VAL 1
    MOV STK T VAL 1
    MOV STK U VAL 1
    MOV STK V VAL 1
    MOV STK W VAL 1
    MOV STK X VAL 1
    MOV STK Y VAL 1
    MOV STK Z VAL 1
    MOV STK a VAL 1
    MOV STK b VAL 1
    MOV STK c VAL 1
    CAL VAL 2
    RET
FUNC LABEL 2
    MOV STK A VAL 1
    MOV STK B VAL 1
    MOV STK C VAL 1
    MOV STK D VAL 1
    MOV STK E VAL 1
    MOV STK F VAL 1
    MOV STK G VAL 1
    MOV STK H VAL 1
    MOV STK I VAL 1
    MOV STK J VAL 1
    MOV STK K VAL 1
    MOV STK L VAL 1
    MOV STK M VAL 1
    MOV STK N VAL 1
    MOV STK O VAL 1
    MOV STK P VAL 1
    MOV STK Q VAL 1
    MOV STK R VAL 1
    MOV STK S VAL 1
    MOV STK T VAL 1
    MOV STK U VAL 1
    MOV STK V VAL 1
    MOV STK W VAL 1
    MOV STK X VAL 1
    MOV STK Y VAL 1
    MOV STK Z VAL 1
    MOV STK a VAL 1
    MOV STK b VAL 1
    MOV STK c VAL 1
    CAL VAL 3
    RET
FUNC LABEL 3
    MOV STK A VAL 1
    MOV STK B VAL 1
    MOV STK C VAL 1
    MOV STK D VAL 1
    MOV STK E VAL 1
    MOV STK F VAL 1
    MOV STK G VAL 1
    MOV STK H VAL 1
    MOV STK I VAL 1
    MOV STK J VAL 1
    MOV STK K VAL 1
    MOV STK L VAL 1
    MOV STK M VAL 1
    MOV STK N VAL 1
    MOV STK O VAL 1
    MOV STK P VAL 1
    MOV STK Q VAL 1
    MOV STK R VAL 1
    MOV STK S VAL 1
    MOV STK T VAL 1
    MOV STK U VAL 1
    MOV STK V VAL 1
    MOV STK W VAL 1
    MOV STK X VAL 1
    MOV STK Y VAL 1
    MOV STK Z VAL 1
    MOV STK a VAL 1
    MOV STK b VAL 1
    MOV STK c VAL 1
    CAL VAL 4
    RET
FUNC LABEL 4
    MOV STK A VAL 1
    MOV STK B VAL 1
    MOV STK C VAL 1
    MOV STK D VAL 1
    MOV STK E VAL 1
    MOV STK F VAL 1
    MOV STK G VAL 1
    MOV STK H VAL 1
    MOV STK I VAL 1
    MOV STK J VAL 1
    MOV STK K VAL 1
    MOV STK L VAL 1
    MOV STK M VAL 1
    MOV STK N VAL 1
    MOV STK O VAL 1
    MOV STK P VAL 1
    MOV STK Q VAL 1
    MOV STK R VAL 1
    MOV STK S VAL 1
    MOV STK T VAL 1
    MOV STK U VAL 1
    MOV STK V VAL 1
    MOV STK W VAL 1
    MOV STK X VAL 1
    MOV STK Y VAL 1
    MOV STK Z VAL 1
    MOV STK a VAL 1
    MOV STK b VAL 1
    MOV STK c VAL 1
    CAL VAL 5
    RET
FUNC LABEL 5
    MOV STK A VAL 1
    MOV STK B VAL 1
    MOV STK C VAL 1
    MOV STK D VAL 1
    MOV STK E VAL 1
    MOV STK F VAL 1
    MOV STK G VAL 1
    MOV STK H VAL 1
    MOV STK I VAL 1
    MOV STK J VAL 1
    MOV STK K VAL 1
    MOV STK L VAL 1
    MOV STK M VAL 1
    MOV STK N VAL 1
    MOV STK O VAL 1
    MOV STK P VAL 1
    MOV STK Q VAL 1
    MOV STK R VAL 1
    MOV STK S VAL 1
    MOV STK T VAL 1
    MOV STK U VAL 1
    MOV STK V VAL 1
    MOV STK W VAL 1
    MOV STK X VAL 1
    MOV STK Y VAL 1
    MOV STK Z VAL 1
    MOV STK a VAL 1
    MOV STK b VAL 1
    MOV STK c VAL 1
    CAL VAL 6
    RET
FUNC LABEL 6
    MOV STK A VAL 27
    MOV STK B VAL 19
    MOV STK C VAL 119
    MOV STK D VAL 5
    MOV STK E VAL 63
    MOV STK F VAL 41
    MOV STK G VAL 91
    MOV STK H VAL 25
    MOV STK I VAL 12
    MOV STK J VAL 133
    MOV STK K VAL 19
    MOV STK L VAL 44
    MOV STK M VAL 62
    MOV STK N VAL 5
    MOV STK O VAL 35
    MOV STK P VAL 19
    MOV STK Q VAL 19
    MOV STK R VAL 158
    MOV STK S VAL 61
    MOV STK T VAL 6
    MOV STK U VAL 125
    MOV STK V VAL 34
    MOV STK W VAL 206
    MOV STK X VAL 94
    MOV STK Y VAL 6
    MOV STK Z VAL 1
    MOV STK a VAL 223
    MOV STK b VAL 7
    MOV REG 0 STK a
    CAL VAL 7
    RET
FUNC LABEL 7
    PRINT REG 0
    RET
