FUNC LABEL 0
    MOV REG 0 VAL 0
    EQU REG 0
    PRINT REG 0
    MOV REG 0 VAL 1
    EQU REG 0
    PRINT REG 0
    MOV REG 0 VAL 5
    EQU REG 0
    PRINT REG 0
    MOV REG 0 VAL 10
    EQU REG 0
    PRINT REG 0
    MOV REG 1 VAL 0
    EQU REG 1
    PRINT REG 1
    PRINT REG 0
    RET
