FUNC LABEL 0
    MOV STK I VAL 0
    MOV STK N VAL 10
    MOV REG 0 STK N
    NOT REG 0
    MOV REG 1 VAL 1
    ADD REG 0 REG 1
    MOV STK N REG 0
    MOV STK A VAL 0
    MOV STK B VAL 1
    MOV REG 0 STK I
    MOV REG 1 STK N
    ADD REG 0 REG 1
    EQU REG 0
    EQU REG 0
    ADD REG 7 REG 0
    RET
    MOV REG 0 STK A
    MOV REG 1 STK B
    ADD REG 0 REG 1
    PRINT REG 0
    MOV STK A STK B
    MOV STK B REG 0
    MOV REG 0 STK I
    MOV REG 1 VAL 1
    ADD REG 0 REG 1
    MOV STK I REG 0
    MOV REG 2 VAL 238
    ADD REG 7 REG 2
    RET
