FUNC LABEL 0
    MOV STK A VAL 0
    MOV STK B VAL 10
    MOV REG 0 STK B
    NOT REG 0
    MOV REG 1 VAL 1
    ADD REG 0 REG 1
    MOV STK B REG 0
    MOV STK C VAL 0
    MOV STK D VAL 1
    MOV REG 0 STK A
    MOV REG 1 STK B
    ADD REG 0 REG 1
    EQU REG 0
    EQU REG 0
    ADD REG 7 REG 0
    RET
    MOV REG 0 STK C
    MOV REG 1 STK D
    ADD REG 0 REG 1
    PRINT REG 0
    MOV STK C STK D
    MOV STK D REG 0
    MOV REG 0 STK A
    MOV REG 1 VAL 1
    ADD REG 0 REG 1
    MOV STK A REG 0
    MOV REG 2 VAL 238
    ADD REG 7 REG 2
    RET
