FUNC LABEL 0
    MOV REG 0 VAL 5
    CAL VAL 1
    MOV REG 0 VAL 6
    CAL VAL 1
    RET
FUNC LABEL 1
    MOV REG 1 VAL 250
    ADD REG 0 REG 1
    EQU REG 0
    MOV REG 2 VAL 2
    ADD REG 7 REG 0
    ADD REG 7 REG 2
    PRINT VAL 2
    RET
    PRINT VAL 1
    RET
