FUNC LABEL 0
    MOV REG 0 VAL 50
    MOV REG 1 VAL 251
    ADD REG 0 REG 1
    PRINT REG 0
    MOV REG 1 VAL 5
    NOT REG 1
    MOV REG 2 VAL 1
    ADD REG 1 REG 2
    ADD REG 0 REG 1
    PRINT REG 0
    RET
