FUNC LABEL 0
    MOV REG 0 VAL 10
    MOV REG 1 VAL 50
    MOV REG 2 VAL 100
    CAL VAL 1
    PRINT REG 0
    PRINT REG 1
    PRINT REG 2
    RET
FUNC LABEL 1
    PRINT REG 0
    PRINT REG 1
    PRINT REG 2
    MOV REG 0 VAL 5
    MOV REG 1 VAL 2
    MOV REG 2 VAL 200
    RET
