FUNC LABEL 0
    MOV STK A VAL 10
    REF STK B STK A
    MOV REG 0 STK B
    CAL VAL 1
    PRINT STK A
    RET
FUNC LABEL 1
    MOV STK A REG 0
    PRINT PTR A
    MOV PTR A VAL 15
    PRINT PTR A
    RET
