FUNC LABEL 0
    CAL VAL 1
    RET
FUNC LABEL 1
    MOV STK A VAL 5
    MOV STK B VAL 5
    MOV STK C VAL 5
    MOV STK D VAL 5
    MOV STK E VAL 5
    MOV STK F VAL 5
    MOV STK G VAL 5
    MOV STK H VAL 5
    MOV STK I VAL 5
    MOV STK J VAL 5
    MOV STK K VAL 5
    MOV STK L VAL 5
    MOV STK M VAL 5
    MOV STK N VAL 5
    MOV STK O VAL 5
    MOV STK P VAL 5
    MOV STK Q VAL 5
    MOV STK R VAL 5
    MOV STK S VAL 5
    MOV STK T VAL 5
    MOV STK U VAL 5
    MOV STK V VAL 5
    MOV STK W VAL 5
    MOV STK X VAL 5
    MOV STK Y VAL 5
    MOV STK Z VAL 5
    MOV STK a VAL 5
    MOV STK b VAL 5
    MOV STK c VAL 5
    CAL VAL 2
    RET
FUNC LABEL 2
    MOV STK A VAL 5
    MOV STK B VAL 5
    MOV STK C VAL 5
    MOV STK D VAL 5
    MOV STK E VAL 5
    MOV STK F VAL 5
    MOV STK G VAL 5
    MOV STK H VAL 5
    MOV STK I VAL 5
    MOV STK J VAL 5
    MOV STK K VAL 5
    MOV STK L VAL 5
    MOV STK M VAL 5
    MOV STK N VAL 5
    MOV STK O VAL 5
    MOV STK P VAL 5
    MOV STK Q VAL 5
    MOV STK R VAL 5
    MOV STK S VAL 5
    MOV STK T VAL 5
    MOV STK U VAL 5
    MOV STK V VAL 5
    MOV STK W VAL 5
    MOV STK X VAL 5
    MOV STK Y VAL 5
    MOV STK Z VAL 5
    MOV STK a VAL 5
    MOV STK b VAL 5
    MOV STK c VAL 5
    CAL VAL 3
    RET
FUNC LABEL 3
    MOV STK A VAL 5
    MOV STK B VAL 5
    MOV STK C VAL 5
    MOV STK D VAL 5
    MOV STK E VAL 5
    MOV STK F VAL 5
    MOV STK G VAL 5
    MOV STK H VAL 5
    MOV STK I VAL 5
    MOV STK J VAL 5
    MOV STK K VAL 5
    MOV STK L VAL 5
    MOV STK M VAL 5
    MOV STK N VAL 5
    MOV STK O VAL 5
    MOV STK P VAL 5
    MOV STK Q VAL 5
    MOV STK R VAL 5
    MOV STK S VAL 5
    MOV STK T VAL 5
    MOV STK U VAL 5
    MOV STK V VAL 5
    MOV STK W VAL 5
    MOV STK X VAL 5
    MOV STK Y VAL 5
    MOV STK Z VAL 5
    MOV STK a VAL 5
    MOV STK b VAL 5
    MOV STK c VAL 5
    CAL VAL 4
    RET
FUNC LABEL 4
    MOV STK A VAL 5
    MOV STK B VAL 5
    MOV STK C VAL 5
    MOV STK D VAL 5
    MOV STK E VAL 5
    MOV STK F VAL 5
    MOV STK G VAL 5
    MOV STK H VAL 5
    MOV STK I VAL 5
    MOV STK J VAL 5
    MOV STK K VAL 5
    MOV STK L VAL 5
    MOV STK M VAL 5
    MOV STK N VAL 5
    MOV STK O VAL 5
    MOV STK P VAL 5
    MOV STK Q VAL 5
    MOV STK R VAL 5
    MOV STK S VAL 5
    MOV STK T VAL 5
    MOV STK U VAL 5
    MOV STK V VAL 5
    MOV STK W VAL 5
    MOV STK X VAL 5
    MOV STK Y VAL 5
    MOV STK Z VAL 5
    MOV STK a VAL 5
    MOV STK b VAL 5
    MOV STK c VAL 5
    CAL VAL 4
    RET
