FUNC LABEL 0
    MOV STK A VAL 5
    MOV STK B VAL 250
    PRINT STK A
    PRINT STK B
    CAL VAL 1
    PRINT STK A
    PRINT STK B
    RET
FUNC LABEL 1
    MOV STK A VAL 151
    MOV STK B VAL 23
    PRINT STK A
    PRINT STK B
    RET
