FUNC LABEL 0
    MOV REG 0 VAL 1
    MOV REG 1 VAL 2
    MOV REG 2 VAL 10
    CAL VAL 1
    RET
FUNC LABEL 1
    PRINT REG 0
    PRINT REG 1
    PRINT REG 2
    ADD REG 1 REG 2
    ADD REG 0 REG 2
    CAL VAL 2
    RET
FUNC LABEL 2
    PRINT REG 0
    PRINT REG 1
    PRINT REG 2
    RET
